### ISSUE TITLE
Unable to use ARC on incognito sessions

### ISSUE THREAD

**Issue by purplemyrtle22** [ThePacielloGroup/ARC-Toolkit#10]
**Describe the bug**

> Add the ability to run ARC on incognito sessions. This used to work before the update.

**To Reproduce**

> Identify any steps required to reproduce the behavior and/or link to a test case that demonstrates the issue.

1. On chrome settings, select the add on and allow in incognito.
2. Create a new incognito session.
3. Access a website -- https://google.com
4. Access ARC toolkit

Test Case (CodePen/JSBin/etc.):

**Expected behavior**

> ARC toolkit should appear.

![image](https://user-images.githubusercontent.com/109261942/178896015-9c1f0f9d-7216-4daf-9170-68c36f247a0d.png)

Actual behaviour: nothing is seen, ARC toolkit does not load.
![image](https://user-images.githubusercontent.com/109261942/178896138-d9c3ff37-0ef6-4c4a-9ac0-3e334f1aafcd.png)

> If applicable, add screenshots to help explain your problem.

**Version information**

- Browser and version:
- ARC Toolkit version: Chrome ARC Toolkit ver 5.2.0

**Additional context**

> Add any other context about the problem here.

**Comment by poorgeek** [comment]
Fixed and will be in the next release
