### ISSUE TITLE
add WAI-ARIA usage checker back into ARC Toolkit

### ISSUE THREAD

**Issue by stevefaulkner** [ThePacielloGroup/ARC-Toolkit#11]
Is your feature request related to a problem? Please describe.

The previous version of ARC Toolkit included the [WAI-ARIA Usage checker](https://thepaciellogroup.github.io/WAI-ARIA-Usage/WAI-ARIA_usage.html). This feature is missing from the new version of ARC Toolkit (5.2.0).
**Additional context**
The inclusion of this in ARC Toolkit is expected and supports the implementation requirements of the [ARIA in HTML](https://w3c.github.io/html-aria/) spec. It would be expected that this tool is pre-installed in the Other tools section
![screenshot of toolkit other tools section](https://user-images.githubusercontent.com/835859/178942457-675db080-6495-4f78-98b6-9ce7ab8e32b7.png)

**Comment by poorgeek** [comment]
Included in the 5.3.0 release
