### ISSUE TITLE
Add TAB Order and HTML labels back into ARC Toolkit

### ISSUE THREAD

**Issue by ClaireHut42** [ThePacielloGroup/ARC-Toolkit#12]
**Is your feature request related to a problem? Please describe.**
> The new version of ARC Toolkit is missing the HTML and TAB labels which woud be displayed on the page being tested.

**Describe the solution you'd like**
> Please add them back in.

**Describe alternatives you've considered**
> Accessibility Insights for Web

**Additional context**
>

**Comment by ferllings** [comment]
Hi Claire,

Could you clarify "...is missing the HTML"

**Comment by poorgeek** [comment]
Support for visualizing the tab order and HTML labels is available in ARC Toolkit 5.4.1
