### ISSUE TITLE
ARC Toolkit panel is blank in the Developer Tools 

### ISSUE THREAD

**Issue by poorgeek** [ThePacielloGroup/ARC-Toolkit#13]
**Describe the bug**

When selecting ARC Toolkit in the Developers Tools, panel is empty, there are no controls or anything.

**To Reproduce**

> Identify any steps required to reproduce the behavior and/or link to a test case that demonstrates the issue.

1. Install or update to ARC Toolkit v5.2.0
2. Accept the required permissions for the extension
3. Open the browser's Developer Tools and select the ARC Toolkit panel

**Expected behavior**

ARC Toolkit and its controls are displayed

**Screenshots**

<img width="520" alt="Screenshot of empty ARC Toolkit panel" src="https://user-images.githubusercontent.com/489299/179290318-d0ba1969-2506-497e-b78f-1289c954d283.png">

**Version information**

- Browser and version: Chrome
- ARC Toolkit version: 5.2.0

**Additional context**

> Add any other context about the problem here.

**Comment by poorgeek** [comment]
This issue is occurring because the browser that Toolkit is installed into does not have access all of the permissions it needs in order to function. This can occur even when the user Agrees to the permissions during the update/install process, but the browser itself is managed by a company's IT Department (or other entity) which controls what rights and permissions installed extensions have access to. 

A first step in determining if this is the cause of your issue is to open the Extension settings in your brower and see if the browser identifies as being managed by the organization.
<img width="336" alt="Screenshot of Chrome indicating the browser is managed by the organization" src="https://user-images.githubusercontent.com/489299/179291439-8b09fd72-703a-4a17-94ec-b711c8f47527.png">

If so, then reach out to your IT Department and let them know that ARC Toolkit requires the following permissions:
- activeTab
- storage
- tabs
- clipboardWrite

**Comment by superterrific** [comment]
I'm having this problem on my personal machine (Mac), what can do I do to ensure the plugin has access to those items? 

I tried uninstalling and reinstalling the plugin with no luck. Also turning off all of my other plugins to make sure there wasn't a conflict.

My work machine administrated by the organization is working fine!

**Comment by Kbridgeford** [comment]
An IT Team is asking where can those permissions be edited?
![Settings ARC Toolkit](https://user-images.githubusercontent.com/104464041/183670981-46454544-6e64-4a8e-9b6d-bcbb8be4df5b.png)

**Comment by poorgeek** [comment]
5.4.1 will no longer display a blank screen but will instead tell you what permissions are missing in your browser. For organization that manage the browser, this will allow you have to have conversation about why additional permissions ARC Toolkit now needs in order to work as expected.
