### ISSUE TITLE
some implicit landmarks not highlighted

### ISSUE THREAD

**Issue by stevefaulkner** [ThePacielloGroup/ARC-Toolkit#18]
**Describe the bug**
it is expected that the highlight landmark elements feature will highlight HTML elements with implicit landmark roles
`header/footer/main/aside` etc

**To Reproduce**

1. Go to https://thepaciellogroup.github.io/AT-browser-tests/test-files/footer.html
2. Click on 'the highlight landmarks button'
4. See result
![footer element test page says Page does not contain any landmark elements](https://user-images.githubusercontent.com/835859/192381706-8bdaa645-84a0-45a1-8907-fa190493d8ba.png)

Test Case (CodePen/JSBin/etc.): https://www.html5accessibility.com/tests/structural-elements.html

**Expected behavior**

`<header>,<footer>, <nav>, <aside>, <main> <form with accname>` elements are highlighted.

**Version information**

- Browser and version: chrome Version 105.0.5195.127 (Official Build) (64-bit)
- ARC Toolkit version: 4.5.2

**Comment by ferllings** [comment]
Working with current dev code. (5.5.0)
So probably fixed in previous or next build
