### ISSUE TITLE
Scan times out for local files

### ISSUE THREAD

**Issue by hanshillen** [ThePacielloGroup/ARC-Toolkit#19]
**Describe the bug**

When scanning a local page, nothing happens until a timeout message is shown.

**To Reproduce**

1. In the 'manage extension' settings for ARK Toolkit, enable "Allow access to file URLs".
2. Open an HTML file from your local file system (url in address bar starts with `file://`).
3. Open the ARC Toolkit panel in DevTools, and click "Run Tests"
4. After a few seconds, message below appears:
    ```
        Problem: Toolkit was unable to complete its scan.

        Reason: timeout
    ```
 

**Expected behavior**

The scan to be performed

**Screenshots**

![image](https://user-images.githubusercontent.com/138848/192693390-ce837916-2236-45fb-88f4-58c79d068f6a.png)

**Version information**

- Browser and version: Chrome 105.0.5195.125 (Official Build) (x86_64)
- ARC Toolkit version: 5.4.2

**Comment by ferllings** [comment]
@hanshillen Could you provide your file?
I'm testing myself with various local files and I don't think it's related to that.

**Comment by hanshillen** [comment]
The file doesn't seem to matter to me, so it's probably something related to my set up 
[issue-19-testcase.html.zip](https://github.com/ThePacielloGroup/ARC-Toolkit/files/9682269/issue-19-testcase.html.zip)

**Comment by ferllings** [comment]
Yes, still can't reproduce with your file.
Do you have anything in the console? Maybe a missing permission?
