### ISSUE TITLE
Reflow and text spacing testing option gone again

### ISSUE THREAD

**Issue by sophieschoice** [ThePacielloGroup/ARC-Toolkit#21]
**Describe the bug**

The options to test for reflow and text spacing are gone again from the ARC toolkit.

**To Reproduce**

Open the ARC Toolkit in your browsers devtool and see that the options are not available anymore.

**Screenshots**

The options to check for reflow and text spacing are gone again

<img width="335" alt="screenshot-l5wV2qVJ@2x" src="https://user-images.githubusercontent.com/2573361/196443227-a59ab366-9781-49c5-b789-596263f1ae45.png">

**Version information**

- Browser and version: Latest Chrome
- ARC Toolkit version: 5.4.2

**Comment by poorgeek** [comment]
@sophieschoice with the addition of the highlighters for headings, images, tab order, etc... added in 5.4.x, we moved the Text Spacing and Page Reflow options to the Page section at the top of Highlighters.
<img width="318" alt="Screenshot showing the new location of Text Spacing and Page Reflow features under Highlighters" src="https://user-images.githubusercontent.com/489299/200063936-89789ef6-ac37-4ab0-bb39-eba9d22f8fd8.png">
