### ISSUE TITLE
scoped testing not working

### ISSUE THREAD

**Issue by stevefaulkner** [ThePacielloGroup/ARC-Toolkit#25]
When the check x node only checkbox is checked, the whole document is still checked

**To Reproduce**

> Identify any steps required to reproduce the behavior and/or link to a test case that demonstrates the issue.

1. Go to https://www.html5accessibility.com/tests/structural-elements.html
2. Click on main in devtools
![main](https://user-images.githubusercontent.com/835859/201968496-481ffd19-b1dd-4a24-a6aa-7d8664e019e4.png)
3. go to toolkit pane, check the scope checkbox and run tests
![main-selected](https://user-images.githubusercontent.com/835859/201968789-d6479d82-6535-4043-a81e-18a099224725.png)
4. when finished note that error list includes issues outside of scoped node
![whole-page](https://user-images.githubusercontent.com/835859/201969236-b9f7f7c3-df72-4949-9c67-0c91af610dd9.PNG)

**Expected behavior**
Only the `main` element and its descendants are tested.

**Version information**

- Browser and version: Version 107.0.5304.107 (Official Build) (64-bit)
- ARC Toolkit version:Version: 5.4.2

**Additional context**
selecting a node does not always result in the scoped testing feature being displayed.

**Comment by ferllings** [comment]
Fixed. Will be merged for the next release.
