### ISSUE TITLE
Iframe issues

### ISSUE THREAD

**Issue by aaronbnb** [ThePacielloGroup/ARC-Toolkit#26]
**Describe the bug**

ARC Toolkit runs its tests on the entire page including inside `<iframe>` elements.  

In the _Results by messages_ and _Results by elements_ panels, for each element located within a page `<iframe>`, the   _Inspect element_ functionality does not work properly. 

In most cases, when the _Inspect element_ button is activated, ARC Toolkit freezes/lags for a second then nothing happens. Toolkit does not switch to showing the element in the Chrome Elements panel.

For assertions such as "Page title is empty", when the _Inspect element_ button is selected, Chrome Developer Tools switches to the Elements panel but selects the `<html>` for the main document rather than the `<html>` within the `<iframe>`.

**To Reproduce**

> Identify any steps required to reproduce the behavior and/or link to a test case that demonstrates the issue.

To see the bug behavior, scan a page which has an `<iframe>` and the `<iframe>` contains elements flagged by ARC Rules. 

Test Case 1:
1. Go to 'https://npr.org'
2. Wait for the Google Ads frames to load.
3. In ARC Toolkit, select 'Run Tests'
4. In _Reveal by messages_ panel, scroll to an instance of 'Page title is empty' which is due to the Google Ads frames.
5. Select _Inspect element_ to see that ARC does not switch to the element or switches to the wrong `<html>` element in the Chrome Elements panel

Test Case 2:
1. Go to 'https://aaronbnb.github.io/acme-insurance'. The page has an `<iframe>` which displays a different GitHub pages site (for a ["Hot Restaurant"](https://aaronbnb.github.io/hot-restaurant/))
2. The "Hot Restaurant" site has several accessibility errors such as the hamburger menu button not having an accessible name.
3. In ARC Toolkit, select 'Run Tests'
4. In _Reveal by messages_ panel, scroll to an instance of an issue within an `<iframe>` which is due to the Google Ads frames.
5. Select _Inspect element_ to see that ARC does not switch to the element.

**Expected behavior**

ARC Toolkit should switch to the correct element in an `<iframe>`.

For assertions such as 'Page title is empty', 'Lang not defined', ARC Toolkit returns "document" as the code snippet. This may be expected behavior but Toolkit users have not understood that "document" indicates an `<iframe>` was flagged. ARC Toolkit must return a code snippet which states that it is an `<iframe>`.

**Screenshots**

![toolkit](https://user-images.githubusercontent.com/11880393/204818827-1b20fbd9-6670-42a7-a1d3-263237e001f9.png)

**Version information**

- Browser and version: Chrome Version 107.0.5304.107 (Official Build) (64-bit)
- ARC Toolkit version: 5.4.2

**Comment by ferllings** [comment]
@aaronbnb I believe this bug as been recently fixed.
The error now correctly indicates the iframe:
<img width="732" alt="Screenshot 2022-12-07 at 15 30 30" src="https://user-images.githubusercontent.com/2118130/206206292-55557509-3d51-43fa-bfde-ecad31055dbd.png">
<img width="721" alt="Screenshot 2022-12-07 at 15 32 13" src="https://user-images.githubusercontent.com/2118130/206206327-9744473c-2953-4412-a96f-8f834586e2d5.png">

**Comment by aaronbnb** [comment]
Thank you for rapid response ARC Toolkit team! That is an awesome improvement to ARC Toolkit. It makes the test results for `iframe` much easier to understand.

@ferllings To be clear, the screenshot you've shared is from the _upcoming_ (version: 5.5) release for ARC Toolkit and that update has been to the Chrome Web Store and is awaiting approval. 

Is this correct? And do you have an estimate for when that update will be available?

When I have access to the latest version of ARC Toolkit, which solves this issue, I will close the issue. Yay!

P.S. I may be filing a feature request for ARC Toolkit to have a setting, a toggle, which allows users to set whether ARC Toolkit should evaluate iframes which have `aria-hidden="true"` attribute applied to them.

**Comment by ferllings** [comment]
@aaronbnb Yes, this is the upcoming version. I'm not sure when it will be available as it looks like Google recently required a little modification.

About hidden iframes, I suggest you to request that under RulesEngine repo (https://github.com/ThePacielloGroup/ARC-RulesEngine/issues)

**Comment by poorgeek** [comment]
These issues have been addressed in ARC Toolkit 5.5.3
