### ISSUE TITLE
Run on selected node feature does not function

### ISSUE THREAD

**Issue by douga11y** [ThePacielloGroup/ARC-Toolkit#28]
**Describe the bug**

When running tests in ARC Toolkit the user has the option to select a node in the Elements pane to limit the scope of what parts of the DOM will be tested against. This feature does not appear to function properly for the following reasons:
- The checkbox for enabling this feature does not display unless the user navigates back and forth from the ARC Toolkit pane.
- After checking the "Run on selected node only" checkbox and running the test, the checkbox disappears and the test results are not limited to the scope of the node that was selected.

**To Reproduce**

1. Go to 'https://www.tpgi.com/'
2. Right click on a section of the page and select the 'Inspect' option (alternatively use a keyboard shortcut to open the developer tools). The Elements pane of the developer tools should appear with the inspected node highlighted.
3. Navigate to the ARC Toolkit pane in the developer tools. 
4. Note that the option to "Run on selected node only" is not present (issue number 1).
5. Navigate back to the Elements pane and select a different node.
6. Navigate back to the ARC Toolkit pane and notice that the "Run on selected node only" checkbox has appeared.
7. Check the "Run on selected node only" checkbox and select the "Run tests" button.
8. Note that the "Run on selected node only" checkbox now disappears and the resulting errors/alerts reported include elements outside of the selected node (issue number 2).

**Expected behavior**

- The option to run on the selected DOM node should be available by default when running ARC Toolkit.
- The results from running tests when the "Run on selected node only" checkbox is checked should only include those from the selected node and its children.

**Screenshots**

![image](https://user-images.githubusercontent.com/3267932/209003211-8578a35d-3172-44d9-8967-4af45852da29.png)

**Version information**

- Browser and version: Google Chrome Version 108.0.5359.124 (Official Build) (x86_64)
- ARC Toolkit version: 5.4.2

**Comment by ferllings** [comment]
I believe this as been fixed in the upcoming 5.5.0 version.

**Comment by poorgeek** [comment]
This feature has been released.
