### ISSUE TITLE
Check Page Reflow toggle

### ISSUE THREAD

**Issue by poorgeek** [ThePacielloGroup/ARC-Toolkit#3]
**Is your feature request related to a problem? Please describe.**

The previous version of ARC Toolkit included the ability to toggle Page Reflow so that SC 1.4.10 can be easily tested. This feature is missing from the new version of ARC Toolkit (5.2.0).

<img width="305" alt="Screenshot of Page Reflow toggle in ARC Toolkit v4" src="https://user-images.githubusercontent.com/489299/178744077-51fe1b6b-1b2c-4b55-bd29-5e323a76313e.png">

**Comment by poorgeek** [comment]
Included in the 5.3.0 release

**Comment by sophieschoice** [comment]
The options to check for reflow and text spacing are disappeared again

<img width="335" alt="screenshot-l5wV2qVJ@2x" src="https://user-images.githubusercontent.com/2573361/196443227-a59ab366-9781-49c5-b789-596263f1ae45.png">
