### ISSUE TITLE
Element inspector feature does not work with SVGs

### ISSUE THREAD

**Issue by mra11yx** [ThePacielloGroup/ARC-Toolkit#30]
Per my testing, the Inspect Element button does nothing when the element to be inspected is an <svg>. This seems to only affect <svg> elements.
![image](https://user-images.githubusercontent.com/17028125/215896954-3b7857a8-4b53-46b0-97ec-27acee1b0de4.png)

ARC Toolkit version: 5.4.2

**Comment by ferllings** [comment]
Can't reproduce with dev build.
