### ISSUE TITLE
No accessible name reported for combobox role with explicit label

### ISSUE THREAD

**Issue by scardamalias** [ThePacielloGroup/ARC-Toolkit#33]
**Describe the bug**

Maybe I'm missing something in how role=combobox is supposed to be used, but I've had the same result testing a combobox example from Dequeue Labs. The component in my app is from Material UI v5.x and I've pulled out all the class names and some extra markup/wrappers for clarity in the reproduction.

ARC Toolkit reports "Input has no accessible name" when:
- input is labeled explicitly by LABEL@FOR=INPUT@ID, and...
- input has role=combobox

**To Reproduce**
Load the following document or try https://dequelabs.github.io/combobo/demo/, and scan with ARC toolkit.
```
<!DOCTYPE html>
<html lang="en">
    <head><title>arc test</title></head>
    <body>
        <form>
            <label data-shrink="false" for="12561899761">
                My Selection
                <span aria-hidden="true"> *</span>
            </label>
            <input aria-invalid="false" id="12561899761"
                aria-expanded="false" aria-autocomplete="list"
                name="mp-lqdjr7sr" required="" type="text"
                role="combobox" value="" />
        </form>
    </body>
</html>
```

**Expected behavior**

ARC Toolkit should not report "input has no accessible name" errors for combobox fields using explicit labels.

These tools had no issue with this markup and correctly matched the label to the input:
- Firefox Accessibility panel
- US SSA ANDI bookmarklet
- AXE DevTools
- WAVE

**Screenshots**

<img width="941" alt="accessible-name-ANDI" src="https://user-images.githubusercontent.com/17724965/233709056-4f0d8631-9ac4-41fd-9f7d-0a4acaeb0f40.png">
<img width="1370" alt="accessible-name-axe-devtools" src="https://user-images.githubusercontent.com/17724965/233709057-138f5795-a6e4-440e-af4d-dc7a1a1b0ae1.png">
<img width="1004" alt="accessible-name-FF-accessibility" src="https://user-images.githubusercontent.com/17724965/233709059-b955dc79-6aae-475a-8e47-86f7d65a73d5.png">
<img width="1073" alt="accessible-name-WAVE" src="https://user-images.githubusercontent.com/17724965/233709062-da039433-c975-4c65-8f80-905b15ecdfa7.png">
<img width="1395" alt="accessible-name-arc-toolkit" src="https://user-images.githubusercontent.com/17724965/233709080-075de108-48e3-443b-842e-fab184e6f9e4.png">

**Version information**

- Browser and version: Chrome 112.0.5615.49 (on OSX 13.3.1)
- ARC Toolkit version: 5.5.3

**Additional context**
Reference:
https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/combobox_role
https://dequelabs.github.io/combobo/demo/ (ARC reports the same error here)

**Comment by stevefaulkner** [comment]
@scardamalias thanks for raising the issue!

```
<label for="combobox-single">Choose Band</label>
<input type="text" class="combobox" id="combobox-single" 
role="combobox" aria-owns="IetjAgR2" aria-autocomplete="list" aria-expanded="false">
```

Can confirm this is a bug, the `input` does have an acc name via the `label` element.  @ferllings @poorgeek

**Comment by ferllings** [comment]
Strange, this is a very basic usecase.
Should be easy to debug and fix.

**Comment by ferllings** [comment]
Found the problem.
Should be fixed on the next release.

**Comment by scardamalias** [comment]
Thank you @stevefaulkner & @ferllings!

**Comment by scardamalias** [comment]
@ferllings, any chance you could share general release timelines or point me towards where to find them? I've run into what may be a related issue to what I reported above and I'd love to test against a newer version before opening a new issue.
