### ISSUE TITLE
ARIA Checker throws error

### ISSUE THREAD

**Issue by stevefaulkner** [ThePacielloGroup/ARC-Toolkit#35]
**Describe the bug**

When activating the ARIA checker (in other tools) nothing happens

**To Reproduce**

1. Go to https://cdpn.io/pen/debug/GRYOama
2. Click on Other tools > ARIA checker
3. no results displayed
4. Console error 

> Refused to load the script 'https://thepaciellogroup.github.io/WAI-ARIA-Usage/aria-usage.js' because it violates the following Content Security Policy directive: "script-src 'self' 'wasm-unsafe-eval' 'inline-speculation-rules'". Note that 'script-src-elem' was not explicitly set, so 'script-src' is used as a fallback.

**Expected behavior**

The results page is displayed.

**Note:** running the [bookmarklet for the ARIA checker](https://thepaciellogroup.github.io/WAI-ARIA-Usage/WAI-ARIA_usage.html) works as expected. I tried several other pages all worked with the bookmarklet, none worked with the toolkit ARIA checker

**Version information**

- Browser and version: Chrome Version 113.0.5672.63 (Official Build) (64-bit)
- ARC Toolkit version: Version: 5.5.3

**Comment by ferllings** [comment]
Ah, probably because Manifest v3 is more strict to load external files.
I probably need to declare it, somewhere.

**Comment by ferllings** [comment]
With Manifest v3 I can't call external JS.
So the only solution is to include the .js in toolkit.

**Comment by poorgeek** [comment]
This appears to have been resolved previously and works correctly in ARC Toolkit 5.7.2. @stevefaulkner please feel free to reopen this issue if you can still reproduce this bug.
