### ISSUE TITLE
ARC shows incorrect error

### ISSUE THREAD

**Issue by alpertron** [ThePacielloGroup/ARC-Toolkit#38]
**Describe the bug**
Having an aria-expanded attribute with role menuitem triggers the error:
The aria-expanded attribute is only allowed on elements with a compatible role="..."

But according to https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-expanded , role menuitem is valid for aria-expanded attribute.

**To Reproduce**

1. With the ARC Chrome extension installed, navigate to https://www.alpertron.com.ar/ECM.HTM
2. Press F12 to enter developer mode.
3. Select ARC Tooklit tab.
4. Press Run Test button.
5. The tool will show 4 errors.

**Expected behavior**

The tool should not indicate errors.

**Screenshots**

**Version information**

- Browser and version: Chrome for Windows 114.0.5735.199
- ARC Toolkit version: 5.5.3

**Comment by ferllings** [comment]
@alpertron, you're correct, but for aria 1.2

The current version of ARC Toolkit uses aria 1.1, and aria-expanded is not in the list of supported attributes: https://www.w3.org/TR/wai-aria-1.1/#menuitem

A new version of Toolkit, with aria 1.2 specs is already in the pipe, and should be available soon.
