### ISSUE TITLE
Skip to main content link target erroneously reported as non focusable 

### ISSUE THREAD

**Issue by jducrot** [ThePacielloGroup/ARC-Toolkit#39]
**Describe the bug**

> The target of the "skip to main content" link on a webpage is reported as non focusable. 

**To Reproduce**

> This can be tested on 

1. Go to https://www.whitehouse.gov/ as of July 2023 
2. Run ARC toolkit
3. Check out 1 report of "Link target not focusable"

**Expected behavior**

> This problem shouldn't be reported in this case. The "skip to main" link properly relocated the keyboard focus to the main landmark with an id of "content" when operated using a keyboard

**Screenshots**

![skip-target-1](https://github.com/ThePacielloGroup/ARC-Toolkit/assets/280674/9151de23-5498-4762-bd8c-ac34e0b23db1)

![skip-target-2](https://github.com/ThePacielloGroup/ARC-Toolkit/assets/280674/2a0f016f-6ddf-466d-b4d3-7493ca9e7da1)

**Version information**

- Browser and version: Windows 10 Chrome Version 114.0.5735.199
- ARC Toolkit version: 5.5.3

**Comment by poorgeek** [comment]
Closing as fixed in ARC Toolkit 5.6.2
