### ISSUE TITLE
Scans in Edge never seem to finish

### ISSUE THREAD

**Issue by cstrobbe** [ThePacielloGroup/ARC-Toolkit#41]
When I run a scan in Edge, the scan never seems to finish. Or should Edge be considered as a non-supported browser?

**To Reproduce**

1. As an example, open [Athlean-X](https://athleanx.com/) in Edge.
2. In ARC Toolkit, click "Run tests".
3. Check whether the scan ever finishes.

**Expected behavior**

* Either the scan finishes,
* or Edge is declared a non-supported browser in the documentation.

**Screenshots**

Spinner after more than a minute:
![image](https://github.com/ThePacielloGroup/ARC-Toolkit/assets/1943277/c3b73a59-91e3-4e1b-80b6-69b5da8cf9ff)

**Version information**

- Browser and version: Edge Version 117.0.2045.41 (Official build) (64-bit) (on Windows 10).
- ARC Toolkit version: 5.5.3.

**Comment by poorgeek** [comment]
@cstrobbe please try this again with the latest ARC Toolkit 5.6.0 release on Oct. 9th. I primarily use Edge with ARC Toolkit and haven't had a problem, but running a scan against the supplied URL just now worked as expected and returned results.

**Comment by cstrobbe** [comment]
Still the same result:
![image](https://github.com/ThePacielloGroup/ARC-Toolkit/assets/1943277/2fb562a9-544a-4e41-987a-3714af289750)

Testpages: [Essential Skills for European Citizens' Initiative Organisers](https://[academy.europa.eu/courses/essential-skills-for-european-citizens-initiative-organisers](https://academy.europa.eu/courses/essential-skills-for-european-citizens-initiative-organisers)) at EU Academy, [Athlean-X](https://athleanx.com/) and [Hybrid Calisthentics](https://www.hybridcalisthenics.com/).

**Comment by poorgeek** [comment]
Retested all 3 pages with the latest version of the ARC Toolkit 5.7.2 in Edge 124.0.2478.105 and all 3 scans complete successfully. 

As of 5.7.0 ARC Toolkit does include additional logging so if you are able to reproduce this still then you should get an error message from the scan as well as a log report that you can post here. Please feel free to reopen this issue if scans of these sites are continuing to fail when using the latest version of ARC Toolkit.

**Comment by cstrobbe** [comment]
This is the error I get when scanning https://athleanx.com/:


> The ARC Rules failed to execute due to invalid JavaScript existing in the page.
ARC's ability to accurately scan for accessibility is limited to environments where features are supported either natively or with accurate polyfills.

> Error Report
Date: 24/05/2024, 21:52:05
Rules Engine: 5.7.2
URL: https://athleanx.com/
UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36 Edg/124.0.0.0
Error: timeout [0% starting...]
