### ISSUE TITLE
ARC Toolkit not displaying Best Practices

### ISSUE THREAD

**Issue by aaronbnb** [ThePacielloGroup/ARC-Toolkit#44]
**Describe the bug**

ARC Toolkit does not display Best Practices. 

**To Reproduce**

> Identify any steps required to reproduce the behavior and/or link to a test case that demonstrates the issue.

1. Go to [Test Site](https://aaronbnb.github.io/scrapboard/svg-test.html)
2. Run Scan
3. The page should be flagged for lack of no `<h1>` Best Practice

**Expected behavior**

ARC Toolkit should display Best Practices when they are enabled to appear.

**Comment by ferllings** [comment]
Fixed in https://dev.azure.com/tpgarc/AAP%20Portal%20R2/_git/845fb0ff-ebfc-4a1d-a198-f201b3667ee7/commit/4715dc98f277a585d2623c5edf94874e802681bf
