### ISSUE TITLE
ARC Toolkit does not display the errors, alerts, and best practices by Topic

### ISSUE THREAD

**Issue by aaronbnb** [ThePacielloGroup/ARC-Toolkit#46]
**Description**

ARC Toolkit's sidebar does not display the errors, alerts, and best practices by Topic.

**To Reproduce**

Run a scan on any page.

**Expected behavior**

ARC Toolkit's findings should be broken down by Topic.

**Screenshots**

<img width="198" alt="screenshot of ARC Toolkit shows that the topic areas are blank" src="https://github.com/ThePacielloGroup/ARC-Toolkit/assets/11880393/14b033b3-d39a-4c6a-a19c-dd742e4a4e7a">

**Version information**
- ARC Toolkit version: 5.6

This issue was raised by numerous organizations using ARC Toolkit.

**Comment by ferllings** [comment]
The problem has been identified in rules engine, not returning the correct topic value

**Comment by aaronbnb** [comment]
ARC Toolkit does not show the assertions by topic area. Should this be marked as completed?

**Comment by ferllings** [comment]
Re-opening until this get the new engine version

**Comment by aaronbnb** [comment]
This issue has been solved 🎉
