### ISSUE TITLE
Does not support <menu> tags

### ISSUE THREAD

**Issue by abbott567** [ThePacielloGroup/ARC-Toolkit#47]
**Describe the bug**

When using a `<menu>` tag with `<li>` children, ARC incorrectly flags it as an error. 

See:
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/menu

**To Reproduce**

1. Test against any menu element. For example:
```html
<menu>
  <li><button id="save">Save for later</button></li>
  <li><button id="share">Share this news</button></li>
</menu>
```
2. Run ARC
3. Observe error:
List item has no list parent
Description: The `<li>` list item elements lack an appropriate `<ol>` (ordered list) or `<ul>` (unordered list) parent element.

**Version information**
- ARC Toolkit version: 5.6.0

**Comment by poorgeek** [comment]
Support for the `<menu>` tag as a valid parent is included with ARC Toolkit 5.7.2.
