### ISSUE TITLE
Run Test on Node Only Difficult/Impossible to Execute

### ISSUE THREAD

**Issue by deconspray** [ThePacielloGroup/ARC-Toolkit#53]
**Describe the bug**

There are times when only a portion, or component of a webpage is needed to be tested. Selecting a node in the DOM, then switching to ARC Toolkit does not present the expected "Run Test on Node Only" panel following the branding. As an alternative, a test is run, and a Node selected, the "Run Test on Node Only" panel still is not presented. 

The presentation of this panel is problematic, and I am sure that many are not even aware of this great feature. Triggering this feature must be more consistent and dependable.

**To Reproduce**
***First scenario***
1. Open the Chrome Dev panel.
2. Select a node in the DOM.
3. Select ARC Toolkit
4. The "Run Test on Node Only" is not presented.

***Second scenario***
1. Open the Chrome Dev panel.
2. Select ARC Toolkit.
3. Run a full page test.
4. After the results are presented, select the Elements option in the Dev Panel, select a node, then select ARC Toolkit. The "Run Test on Node Only" is not presented.

Test Case (CodePen/JSBin/etc.):

**Expected behavior**

The "Run Test on Node Only" feature is presented.

**Screenshots**

> If applicable, add screenshots to help explain your problem.

**Version information**

- Browser and version: Chrome 120.0.6099.216 (Official Build) (64-bit)
- ARC Toolkit version: 5.6.0

**Additional context**

> Add any other context about the problem here.

**Comment by ferllings** [comment]
I believe it has been fixed in the dev. branch

**Comment by poorgeek** [comment]
Closing this issue as the selected node does appear in ARC Toolkit 5.7.2.
