### ISSUE TITLE
Failure when running tests with "ARC Rules failed to execute due to invalid JavaScript…"

### ISSUE THREAD

**Issue by jliverse** [ThePacielloGroup/ARC-Toolkit#55]
**Describe the bug**

> Pages with HTML markup containing a `TABLE` in some combinations may fail with the alert message:

The ARC Rules failed to execute due to invalid JavaScript existing in the page.
ARC's ability to accurately scan for accessibility is limited to environments where features are supported either natively or with accurate polyfills.

**To Reproduce**

1. On a Chrome browser with the ARC Toolkit installed and enabled, navigate to [the minimal test case](https://codepen.io/jliverse/pen/KKYjVgV).
2. Right–click on the preview frame and choose **Inspect**. The Chrome Dev Tools panel will load.
3. Choose the **ARC Toolkit** tab and choose **Run tests** to execute the rules for the ARC Toolkit for the extension.
4. An alert message fills the results panel with the text: _The ARC Rules failed to execute due to invalid JavaScript existing in the page.
ARC's ability to accurately scan for accessibility is limited to environments where features are supported either natively or with accurate polyfills._ We expect that pages without JavaScript should not cause the extension to fail with an error reporting the presence of invalid JavaScript.

Test Case (CodePen/JSBin/etc.): https://codepen.io/jliverse/pen/KKYjVgV

**Expected behavior**

> We expect a results panel without an alert message. We expect an `H2` containing a heading _Results by messages_ and a non-zero number of errors, alerts or best practices.

**Screenshots**

> 🚫 None.

**Version information**

- Browser and version: Version 124.0.6367.91 (Official Build) (arm64)—Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36
- ARC Toolkit version: 5.7.0

**Additional context**

> The _Error Report_ has a **Save report** option, attached below:

```html
<div data-v-4af5ae60="" class="p-4"><div data-v-4af5ae60="" class="alert alert-danger" role="alert"><p data-v-4af5ae60="">The ARC Rules failed to execute due to invalid JavaScript existing in the page. <br data-v-4af5ae60="">ARC's ability to accurately scan for accessibility is limited to environments where features are supported either natively or with accurate polyfills.</p></div><div data-v-4af5ae60="" class="d-flex justify-content-end" style="gap: 1rem;"><button data-v-4af5ae60="" class="btn btn-primary float-end" aria-expanded="false"><svg data-v-4af5ae60="" class="svg-inline--fa fa-caret-right" aria-hidden="true" focusable="false" data-prefix="fas" data-icon="caret-right" role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 512"><path class="" fill="currentColor" d="M246.6 278.6c12.5-12.5 12.5-32.8 0-45.3l-128-128c-9.2-9.2-22.9-11.9-34.9-6.9s-19.8 16.6-19.8 29.6l0 256c0 12.9 7.8 24.6 19.8 29.6s25.7 2.2 34.9-6.9l128-128z"></path></svg>&nbsp;View Error report</button><button data-v-4af5ae60="" type="button" class="btn btn-dark float-end">Save report</button></div><div data-v-4af5ae60="" style="display: none;"><h1 data-v-4af5ae60="">Error Report</h1><div data-v-4af5ae60=""><strong data-v-4af5ae60="">Date:</strong> 5/2/2024, 11:10:19 AM</div><div data-v-4af5ae60=""><strong data-v-4af5ae60="">Rules Engine:</strong> 5.7.0</div><div data-v-4af5ae60=""><strong data-v-4af5ae60="">URL:</strong> https://codepen.io/jliverse/pen/KKYjVgV</div><div data-v-4af5ae60=""><strong data-v-4af5ae60="">UserAgent:</strong> Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36</div><div data-v-4af5ae60=""><strong data-v-4af5ae60="">Error:</strong> arc has not been correctly injected [0% starting...]</div><!----><!----></div></div>
```

**Comment by poorgeek** [comment]
Thank you @jliverse. We're looking into why Toolkit is having a problem with the provided sample.

**Comment by ferllings** [comment]
Thanks for the codepen, that was really helpful.

(Note: fixed in https://github.com/ThePacielloGroup/ARC-RulesEngine/pull/493)

**Comment by handyaputra** [comment]
Hi! I've got the similar error message just recently after updating to 5.7.0
 
> The ARC Rules failed to execute due to invalid JavaScript existing in the page.
> ARC's ability to accurately scan for accessibility is limited to environments where features are supported either natively or with accurate polyfills.
 
```
Error Report
Date: 5/6/2024, 2:45:35 PM
Rules Engine: 5.7.0
UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36 Edg/124.0.0.0
Error: Rules Engine failed to execute: SecurityError: Failed to read the 'cssRules' property from 'CSSStyleSheet': Cannot access rules [0% starting...]
```

Do you think this issue will be resolved with that pull request too? Thanks in advance!

**Comment by ferllings** [comment]
@handyaputra No that's a different error.
Please open a new ticket with an url we can test, or sample code

**Comment by poorgeek** [comment]
@jliverse ARC Toolkit 5.7.1 has been submitted to the Google Chrome store for review and should be published soon. Thank you again for the Codepen that really helped us identify the issue and resolve it in a short amount of time.
