### ISSUE TITLE
Highlight feature for Headings and Buttons no longer work in the 5/1/2024 Version 5.7.0

### ISSUE THREAD

**Issue by kabsas** [ThePacielloGroup/ARC-Toolkit#56]
Highlight feature for Headings and Buttons no longer work in the 5/1/2024 Version 5.7.0

**To Reproduce**

1. Go to https://www.tpgi.com/
2. Go to the ARC Toolkit in Chrome DevTools
3. Select "Highlight"
4. Select "Headings" 
5. Select "Buttons"

**Expected behavior**
Headings and buttons are found, listed, and highlighted.

**Actual behavior**
Toolkit indicates there are no heading or buttons.

**Version information**

- Browser and version: Chrome
- ARC Toolkit version: 5.7.0

**Comment by ferllings** [comment]
(Fixed in Azure PR 2385)

**Comment by poorgeek** [comment]
The fix for this issue was released today in ARC Toolkit 5.7.2.
