### ISSUE TITLE
Query with 5.7.1

### ISSUE THREAD

**Issue by dinutraveltickets** [ThePacielloGroup/ARC-Toolkit#57]
I am getting below Error while Run the test with Arc 5.7.1 as

    "Duplicate For and id" even though I don't have duplicate ids. There are no errors with the previous version also. Could you please advise on this.

**Comment by poorgeek** [comment]
Hi @dinutraveltickets can you provide us with more information so that we can try to reproduce your issue? For instance is this occurring on a public facing webpage you can send us the URL to? 
Without more information it will be difficult for us to address the issue.

**Comment by dinutraveltickets** [comment]
Hi Team,

The issue we are getting, we tried to scan google.com and got the same
issue there also.

Please find below sample code and arc-error screen shot which we scanned at
our end and there are not duplicate ids only we have single radio button

<div>
<span><input type="radio" id="pankaj123" name="test1"
aria-label="TD008888213813" /></span>
<span><input type="radio" name="test2" aria-label="TD008888213812" /></span>
</div>

     1. If we click on run test first time not showing errors
[image: image.png]

2. Again Click on Run test
[image: image.png]



Thanks & Regards
Dinesh G.

**Comment by poorgeek** [comment]
Thank you @dinutraveltickets. For some reason your images didn't post here, but they did come through in your submission to our helpdesk. I've been able to reproduce the issue and will have a developer look into the issue.

**Comment by dinutraveltickets** [comment]
Thanks for the update Justin, Can you please let us know when the issue
will be resolved?

Regards
Dinesh G.

**Comment by ferllings** [comment]
(Fixed in Rules Engine PR #494)

**Comment by dinutraveltickets** [comment]
Thank you ferllings, when can we expect this update in Crome extension?

**Comment by dinutraveltickets** [comment]
> (Fixed in Rules Engine PR #494)

Hi ferlling, when can I expect this update on live in Chrome browser extension? as we are in the middle of testing.
Both issues "Duplicate for and Ids" and "Duplicate Labels".

**Comment by ferllings** [comment]
I'm afraid I can't give you an exact date, as we may want to add a few more fixes, and also it depends of the Google Store approval time.

**Comment by dinutraveltickets** [comment]
Thanks for the update ferllings. I understand, but as we have crucial timeline to go into live. So, if possible, could you please let me know the tentative timeline for your release.

**Comment by poorgeek** [comment]
@dinutraveltickets the fix for this issue was released today in ARC Toolkit 5.7.2.

**Comment by dinutraveltickets** [comment]
Thanks for the update poorgreek
