### ISSUE TITLE
Failure when running tests with "ARC Rules failed to execute due to invalid JavaScript…"

### ISSUE THREAD

**Issue by JesusGonzalezA** [ThePacielloGroup/ARC-Toolkit#58]
**Describe the bug**

> Pages with HTML markup containing a style attribute using '@import' fail ARC Toolkit scan with error message: "The ARC Rules failed to execute due to invalid JavaScript existing in the page.
ARC's ability to accurately scan for accessibility is limited to environments where features are supported either natively or with accurate polyfills."

**To Reproduce**

> Using a CHROME browser with ARC Toolkit installed and enabled
1. Go to [minimal case](https://jesusgonzaleza.github.io/ARC-Toolkit-error-5.7.1/)
2. Right–click and choose Inspect. The Chrome Dev Tools panel will load.
3. Choose the ARC Toolkit tab and choose Run tests to execute the rules for the ARC Toolkit for the extension.
4. An alert message fills the results panel with the text: The ARC Rules failed to execute due to invalid JavaScript existing in the page.
ARC's ability to accurately scan for accessibility is limited to environments where features are supported either natively or with accurate polyfills.

Test Case (CodePen/JSBin/etc.): [minimal case](https://jesusgonzaleza.github.io/ARC-Toolkit-error-5.7.1/)

**Expected behavior**

> ARC Toolkit being able to run a scan over the page

**Screenshots**

**Version information**

- Browser and version: 124.0.6367.158 (Build oficial) (64 bits) (cohort: Control) 
- ARC Toolkit version: 5.7.1

**Additional context**

**Comment by ferllings** [comment]
I confirm the issue

**Comment by wegnertm** [comment]
following. I'm getting the same issue.

**Comment by ferllings** [comment]
(Tracked via Azure 10751)

**Comment by ferllings** [comment]
(Fixed in RulesEngine PR 496)

**Comment by poorgeek** [comment]
The fix for this issue was released today in ARC Toolkit 5.7.2.
