### ISSUE TITLE
 toolkit is attempting to access the 'cssRules' property in a way that is causing a security error

### ISSUE THREAD

**Issue by SabAnjum** [ThePacielloGroup/ARC-Toolkit#61]
I am writing to report an issue we are experiencing with the ARC Toolkit on our platform.

Recently, we have encountered difficulties while trying to use the ARC Toolkit. It appears that the toolkit is attempting to access the 'cssRules' property in a way that is causing a security error. This occurs if our CSS file has imported the other CSS file or resources.

We have attempted to troubleshoot the issue internally, but have not been successful in resolving it. Could you please investigate this matter further and provide us with guidance on how to resolve this security error?

<img width="1771" alt="Screenshot 2024-05-17 at 9 44 43 AM" src="https://github.com/ThePacielloGroup/ARC-Toolkit/assets/67508678/0d2729c3-bdab-44ff-8a13-d2cdbda53dc6">

**Comment by ferllings** [comment]
Thanks @SabAnjum. This issue has already been submitted and fixed for the next release.

**Comment by SabAnjum** [comment]
@ferllings What is the expected date for releasing the next build?

**Comment by poorgeek** [comment]
@SabAnjum the fix for this issue was released today in ARC Toolkit 5.7.2.
