### ISSUE TITLE
Scrollable Element is not focusable

### ISSUE THREAD

**Issue by dinutraveltickets** [ThePacielloGroup/ARC-Toolkit#62]
I have Datatable with scrollable options as it contains more columns. And data in DataTable don't have any focusable elements.

When I access ARC Toolkit Run Test It is showing "Scrollable Element is not focusable" error. If I add tabindex to the scrollable element that error is not coming.

Could you please let me know is this expected, because this error is not there in previous version. PFA screen shot.

![image](https://github.com/ThePacielloGroup/ARC-Toolkit/assets/169297814/67ee716b-b6e6-4a4a-8b10-4a24e6226e3e)

Thanks & Regards
Dinesh G.

**Comment by ferllings** [comment]
hi @dinutraveltickets, is possible to get an url, or the source code of the table only?

**Comment by dinutraveltickets** [comment]
Sure Ferlling, PFA attached source code and screen shot

![image](https://github.com/ThePacielloGroup/ARC-Toolkit/assets/169297814/1a4d0c1e-5db2-410e-8774-e5a257d30f4e)
[table-sourcecode.txt](https://github.com/ThePacielloGroup/ARC-Toolkit/files/15391198/table-sourcecode.txt)

**Comment by dinutraveltickets** [comment]
@ferllings, have you got any chance to look into this?

**Comment by ferllings** [comment]
@dinutraveltickets Not yet.
I'll add a note here, if I'm (or not) able to reproduce.

**Comment by ferllings** [comment]
I had a look and we believe this is correct: The rule was recently introduced, and it flags your table because the scrollbar is set on the table (probably using css overflow). And if the table is not focusable, there is no way for a keyboard user to move the slider.

**Comment by dinutraveltickets** [comment]
Thanks for the update @ferllings
