### ISSUE TITLE
No info displayed after clicking inspect then arc toolkit on any URL

### ISSUE THREAD

**Issue by ohughesrnib** [ThePacielloGroup/ARC-Toolkit#7]
**Describe the bug**

No info displayed after clicking inspect then arc toolkit on any URL

**To Reproduce**

1. Go to '.www.bbc.co.uk'
2. Click on '.inspect '
3. Scroll  to 'arc toolkit'
No content is displayed where it was. It me be that I need to set traffic to your site to avoid our proxy. What is the URL that should be whitelisted? I've tried *.tpgi.com. This was working until yesterday.

**Comment by poorgeek** [comment]
@ferllings to my knowledge there are no calls from the Toolkit out to an external site that might involve a proxy server. Can you confirm?

**Comment by ferllings** [comment]
@poorgeek That's correct: toolkit doesn't call any external url. All assets are local.

**Comment by poorgeek** [comment]
@ohughesrnib Can you provide any additional information on what you're experiencing? Are you trying to use Toolkit in Incognito mode (see #10)? Or is your browser managed by your company/organization (see #13)?

**Comment by poorgeek** [comment]
5.4.1 will no longer display a blank screen but will instead tell you what permissions are missing in your browser. For organization that manage the browser, this will allow you have to have conversation about why additional permissions ARC Toolkit now needs in order to work as expected.
