### ISSUE TITLE
Add visual indication of the elements called out by ARC Toolkit

### ISSUE THREAD

**Issue by douga11y** [ThePacielloGroup/ARC-Toolkit#8]
**Is your feature request related to a problem? Please describe.**
> In the previous version of ARC Toolkit when a category or individual failure/warning/etc. was interacted with there was visual feedback on the page about the related element. For example, if looking at a heading element, hovering over the element in the test results would visually highlight it on the page.

**Describe the solution you'd like**
> Add this feature back into the new version of ARC Toolkit (preferably in a way that does not rely on mouse events only).

**Describe alternatives you've considered**
> Use a different testing tool such as WAVE.

**Additional context**
> For people outside of TPGi who use this tool, visual/exploratory feedback is heavily relied upon. Without parody of the old version I would think clients would consider Toolkit sub-par compared to competing tools like WAVE.

**Comment by ferllings** [comment]
This feature is already implemented in Toolkit, but instead of hovering you need to 'open' the result.
Like in this screencapture.
![Screenshot 2022-08-11 at 11 58 10](https://user-images.githubusercontent.com/2118130/184109398-ed66bc1d-95dd-4775-a8e6-519a024bb336.png)

**Comment by douga11y** [comment]
I think there was a bug with this feature when I initially logged it as the highlight was not showing up even if the item was expanded. Since it is working now I will close this request.
