### ISSUE TITLE
Add the ability to run individual tests

### ISSUE THREAD

**Issue by douga11y** [ThePacielloGroup/ARC-Toolkit#9]
**Is your feature request related to a problem? Please describe.**
> In the previous version of ARC Toolkit you had the ability to run tests only for a specific category of content (e.g., Headings, Tables, etc.). This no longer appears to be the case in v5. All of the tests must be run at once which can be inconvenient if the page is large (given that the tests are quite slow to run now in comparison to the previous version). This also makes it a larger cognitive load to use as looking for results on any one particular failure requires sifting through all failures on the page.

**Describe the solution you'd like**
> Add the ability to run tests for individual categories (or I guess they're called "Topics" in the interface) instead of only one "Run tests" button that does everything.

**Describe alternatives you've considered**
> n/a

**Additional context**
> Looking for parody with the previous version of Toolkit. I've seen multiple clients use this to quickly look at specific types of content by running only the tests for that category. They won't be able to do that anymore.

**Comment by poorgeek** [comment]
Ability to run individual tests is available in ARC Toolkit 5.4.1
